/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ccm.usbaudiodemo.usbcontrol;

public class USBTestNativeJNI {
  public final static native long new_USBControl();
  public final static native void delete_USBControl(long jarg1);
  public final static native boolean USBControl_initUSB(long jarg1, USBControl jarg1_);
  public final static native void USBControl_cleanUp(long jarg1, USBControl jarg1_);
  public final static native void USBControl_restartUSBAudioManager(long jarg1, USBControl jarg1_);
  public final static native boolean USBControl_initUSBDevice(long jarg1, USBControl jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native String USBControl_getOpenDeviceErrorMessage(long jarg1, USBControl jarg1_);
  public final static native boolean USBControl_isAudioDevicePresentForLinux(long jarg1, USBControl jarg1_);
  public final static native boolean USBControl_startUSBTransfers(long jarg1, USBControl jarg1_, boolean jarg2, String playName, boolean jarg3, String recName, int jarg4, boolean jarg5, int jarg6, int jarg7);
  public final static native void USBControl_stopUSBTransfers(long jarg1, USBControl jarg1_);
  public final static native void USBControl_setUSBSampleRate(long jarg1, USBControl jarg1_, int jarg2);
  public final static native boolean USBControl_startOpenSLES(long jarg1, USBControl jarg1_, boolean jarg2, boolean jarg3, int jarg4, int jarg5, int jarg6);
  public final static native void USBControl_stopOpenSLES(long jarg1, USBControl jarg1_);
}
